### ISSUE TITLE
Multiple account issues

### ISSUE THREAD

**Issue by QuantumLeap-us** [Widiskel/birds-sui-bot#1]
![image](https://github.com/user-attachments/assets/6f58d95c-de9a-4696-85ea-efedb2aab1fe)
![image](https://github.com/user-attachments/assets/d50228d3-dc46-43f8-8517-aa857a3dde40)
I added more than one account but only three show up?

**Comment by Widiskel** [comment]
it just twist display issue, but other account is running just not showed up
