### ISSUE TITLE
err0r

### ISSUE THREAD

**Issue by AntiWarforever** [Widiskel/birds-sui-bot#10]
```
================= Account 7017313764 =============
Name         : lord  SUI
Balance      : - BIRDS

Status : Error : Invalid checksum for 11fdaca97d6ef9d3xxxxxxxxxexxx1737db68df3c872916708d9337d0dd4, Retrying after 5
 Seconds
Delay : Delaying for 0 Hours 0 Minutes 1 Seconds
==============================================
-
================= Account 7381962078 =============
Name         : momentom"
Balance      : - BIRDS

Status : Error : Unknown character b, Retrying after 5 Seconds
Delay : Delaying for 0 Hours 0 Minutes 2 Seconds
==============================================
```
two error whats is checksum for wallet?
and give me your telegram channel , you don't put channel link in your description

**Comment by Widiskel** [comment]
i put it on readme.md, make sure you use correct private key it begin with `suiprivxxxx`

**Comment by AntiWarforever** [comment]
> i put it on readme.md, make sure you use correct private key it begin with `suiprivxxxx`

I create wallet in bird sui game and all wallet dont begin with word 'suipriv' 
![Uploading Screenshot_2024-11-01-17-33-57-605_com.polestar.super.clone-edit.jpg…]()

**Comment by AntiWarforever** [comment]
[
      "c11ce70xxxxxxxxxxx27f2450e8cf6182d7454ebb625f6cf0f326c94f",
      "accounts/query-1",
    ],
    this is true format?
