### ISSUE TITLE
Help me seeting cofig for wallet

### ISSUE THREAD

**Issue by hengkyhks** [Widiskel/birds-sui-bot#4]
how to write it correctly ?

export class Config {
  static TELEGRAM_APP_ID = undefined; // YOUR APP ID EX : 324893724923
  static TELEGRAM_APP_HASH = undefined; // YOUR APP HASH EX: "aslkfjkalsjflkasf"
  static USEONCHAINTX = true; // SET To TRUE IF YOU WANT TO USE ONCHAIN TX FOR CHECK IN AND UPGRADE
  static USERWALLET = [
    [
      "0x732d2ea39ce03b14ac1c8d925650f61c64cxxxxxxx",
      "accounts/query-1",
    ],
    [
      "0x915af2a454eeaefa1b80e1a3e36b53ea214bf78xxxxxxxx",
      "accounts/query-2",
    ],
  ];
}

**Comment by Widiskel** [comment]
you need sui private key not address

**Comment by hengkyhks** [comment]
still error

![image](https://github.com/user-attachments/assets/7175b8d9-d9ed-4011-a6b9-9ee9f13e66ba)

**Comment by hengkyhks** [comment]
bisakah anda memberikan saya contohnya

**Comment by Widiskel** [comment]
join telegram and ask there
