### ISSUE TITLE
what is this?

### ISSUE THREAD

**Issue by AntiWarforever** [Widiskel/birds-sui-bot#6]
![Caz](https://github.com/user-attachments/assets/b1fac939-fac0-427c-8f89-5d90c9aba133)
I select 3 but say me phone number
app/index.js have problem <3

**Comment by Widiskel** [comment]
create account first, make sure you use old telegram if you use session , or use query instead

**Comment by AntiWarforever** [comment]
after 3 day try, Now I realized that it does not work based on the session
just Query...

**Comment by AntiWarforever** [comment]
after 30 min query ids expire can made on session please?
