### ISSUE TITLE
still error

### ISSUE THREAD

**Issue by hengkyhks** [Widiskel/birds-sui-bot#8]
![image](https://github.com/user-attachments/assets/045cd50d-fef5-4b3a-8bf4-cce3c6f8f3ed)

**Comment by hengkyhks** [comment]
xxxx its sensor

**Comment by Widiskel** [comment]
no need YOUR SUI XXX , just paste your pk and accounts folder inside " "

**Comment by Widiskel** [comment]
it just a guide text
