### ISSUE TITLE
Ask about the format

### ISSUE THREAD

**Issue by alextelex437** [Widiskel/birds-sui-bot#9]
![image](https://github.com/user-attachments/assets/fac8919e-64f2-4bfe-ab1e-28297be181ce)

Hey, I wanted to ask if my format is correct; the bot reported an incorrect wallet format " Status : Cannot Get Wallet Address Skipping..."

**Comment by AntiWarforever** [comment]
I tried for three days, I still don't understand how it works, I just know that the session doesn't work
If I understand, I will help you

**Comment by Widiskel** [comment]
the private key is correct, but it dont need query id on that file, it just need your accounts path, when you start the bot you first create account (session or query) , nah u just need to provide the path to the session folder like the example template
